name: CI — Vite & Gourmand

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installation Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Installation des dépendances
        working-directory: ./backend
        run: npm install

      - name: Génération Prisma Client
        working-directory: ./backend
        run: npx prisma generate

      - name: Vérification syntaxe
        working-directory: ./backend
        run: node --check src/server.js
